#!/bin/bash

set -e

function test_file
{
    file="${1}"
    echo $file | grep 'web/app' || return 0
    unset GIT_DIR
    dir=`dirname $0`
    file=`echo $file | sed -e s:web/app/::g`
    if echo $file | grep models > /dev/null
    then
        object=`echo $file | sed -e s:models/::g -e s:\.rb::g`
        echo "--checking autotest for: $object--"
        ruby -I web/test web/test/unit/${object}_test.rb
        continue
    fi
    if echo $file | egrep "views" > /dev/null
    then
        #rake
        object=`echo $file | sed -e s:views/::g -e s:/.*::g`
        if [ ! -f "web/test/functional/${object}_controller_test.rb" ] ; then
            continue
        fi
        echo "--checking autotest for: $object--"
        ruby -I web/test web/test/functional/${object}_controller_test.rb
        continue
    fi
    echo "*** I Don't know how to test $file ***"
}

case "${1}" in
    --about )
        echo "Check that existing autotests for files that are being commited are not currently failing"
        ;;
    * )
        for file in `git diff-index --cached --name-only HEAD` ; do
            test_file "${file}"
        done
        ;;
esac
