Document: githaven
Title: Debian githaven Manual
Author: <insert document author here>
Abstract: This manual describes what githaven is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/githaven/githaven.sgml.gz

Format: postscript
Files: /usr/share/doc/githaven/githaven.ps.gz

Format: text
Files: /usr/share/doc/githaven/githaven.text.gz

Format: HTML
Index: /usr/share/doc/githaven/html/index.html
Files: /usr/share/doc/githaven/html/*.html
