#!/bin/sh -x
# postinst script for githaven
#
# see: dh_installdeb(1)

set -e

#DEBHELPER#

. /usr/share/debconf/confmodule

case "${1}" in
    configure)
        db_version 2.0

        db_get githaven/username
        _USERNAME="${RET:-git}"
        db_get githaven/directory
        _HOMEDIR="${RET:-/var/git}"

        db_stop

        if ! getent passwd | grep -q "^${_USERNAME}:"
        then
            adduser \
              --system \
              --shell /bin/sh \
              --gecos 'git repository hosting' \
              --group \
              --disabled-password \
              --no-create-home \
              --home ${_HOMEDIR} \
              --quiet \
              ${_USERNAME}
        else
            echo "User (${_USERNAME}) already exists, user was not created."
            currentuserhomedir=`getent passwd | grep "${_USERNAME}" | awk -F':' '{ print $6 }'`
            if [ "${_HOMEDIR}" != "${currentuserhomedir}" ] ; then
            echo "WARNING: ******"
            echo "WARNING: The existing user \"${_USERNAME}\" home directory does not point to the expected location: \"${_HOMEDIR}\", it points to \"${currentuserhomedir}\""
            echo "WARNING: GitHaven will not work properly until this is fixed."
            echo "WARNING: ******"
            fi
        fi

        if [ ! -d "${_HOMEDIR}" ] ; then
            mkdir -p ${_HOMEDIR}
            mkdir -p ${_HOMEDIR}/.ssh -m 700

            mkdir -p ${_HOMEDIR}/githaven
            cd ${_HOMEDIR}/githaven
            set +e
            githaven-makedomaininstall
            if [ $? -ne 0 ] ; then
                echo "There was a problem configuring GitHaven, aborting"
                rm -rf "${_HOMEDIR}"
                return 1
            fi
            set -e
            cd -

            chown ${_USERNAME}:${_USERNAME} --no-dereference --recursive ${_HOMEDIR}
        else
            #if [ -d ${_HOMEDIR}/githaven/db ] ; then
                #cd ${_HOMEDIR}/githaven/
                #rake db:migrate
                #RAILS_ENV=production rake db:migrate
            #fi
            echo
            echo "githaven directory (${_HOMEDIR}) already exists, doing nothing."
            echo "Make sure the directory is recursively owned by (${_USERNAME})."
        fi

        apache="/etc/apache2/sites-available/"
        cat /usr/share/githaven/099-githaven | sed -e "s:\ ~git:\ ${_HOMEDIR}:g" > $apache/099-${_USERNAME}-githaven

        a2dissite default
        a2ensite 099-${_USERNAME}-githaven
        apache2ctl restart

        echo
        echo "GitHaven is now installed and should be running at \"`hostname`\" in your web browser."
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)

        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
