#!/bin/bash
files=`ls -1`
sha="HEAD"
while [ ! -z "${files}" ] ; do
    sha=`git rev-list -1 ${sha} -- .`
    if [ -z $sha ] ; then
        break;
    fi
    file=`git show $sha | grep -e '^+++' | grep -v '/dev/null' |sed -e 's/+++ b\///g' -e 's_/.*__g' | grep -v '^$' | uniq`
    for f in $file; do
        echo "$files" | grep "^${f}$" > /dev/null 2>&1
        if [ $? -eq 0 ] ; then
            echo "$sha $f"
            files=`echo "${files}" | egrep -v "^$f"`
        fi
    done
    sha="${sha}^"
done
